name: Deploy Mi Tienda

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 24

      - name: Install and Build
        run: |
          cd mi-tienda
          npm install
          npm run build

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          # Si después del build ves que la carpeta se crea dentro de mi-tienda:
          path: ./mi-tienda/dist

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4